image: node:20.17.0

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - rm -rf node_modules package-lock.json
    - npm install
    - npx ng build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  script:
    - rm -rf public/*
    - mv dist/daxa/browser/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"