image: node:18 # Utiliza la imagen de Node.js que se necesita para Angular

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli # Instala Angular CLI globalmente

build:
  stage: build
  script:
    - npm install # Instala las dependencias del proyecto
    - ng build --prod # Construye el proyecto en modo producción
  artifacts:
    paths:
      - dist/ # La carpeta que contiene los archivos construidos

deploy:
  stage: deploy
  script:
    - mv dist/tu-proyecto /public # Mueve los archivos construidos a la carpeta pública
  artifacts:
    paths:
      - public
  only:
    - main # Despliega solo cuando haya cambios en la rama principal
